# Generated by Django 5.2.6 on 2025-10-27 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='Profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_realizados', to='clientes.profissional', verbose_name='Profissional Agendado'),
            preserve_default=False,
        ),
    ]
