# Generated by Django 5.2.6 on 2025-10-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_agendamento_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Agendamento Confirmado'),
        ),
    ]
