# Generated by Django 5.2.6 on 2025-11-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_agendamento_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='profissionais_aptos', to='clientes.servico'),
        ),
    ]
